# .semver.yml

# See: https://github.com/carloscuesta/gitmoji/blob/master/src/data/gitmojis.json

# Release Branches
branches: [ main ]

# gitmoji semver settings
# You can override the default values to suit your project.
semver:
  #  minor:
  #    - lipstick
  patch:
    - loud_sound
    - mute
  #  none: # gitmoji.json "semver": null is convert to none
  #    - pencil2
  ignore: # not add in release-template.hbs
    - construction